-- Migration: Add content for Chapters 8-14 (Distributed Systems)
-- Run after 005-fishbook-distributed-systems.sql
-- wrangler d1 execute gtl-db --remote --file=./src/db/migrations/006-fishbook-chapters-8-14-content.sql

-- Chapter 8: Introduction and Overview (Distributed Systems)
INSERT INTO flashcards (module_id, front, back)
SELECT m.id, f.front, f.back FROM modules m,
(SELECT 'What is the difference between concurrent and parallel execution?' as front, 'Concurrent: both sequences are in progress, but only one executes at any moment (two queues, one coffee machine). Parallel: steps execute simultaneously by multiple processors (two queues, two coffee machines). Concurrent operations overlap in time; parallel ones run on multiple CPUs.' as back UNION ALL
SELECT 'What are consistency models in distributed systems?', 'Models that describe concurrent executions and establish the order in which operations can be executed and made visible to participants. They can constrain or relax the number of states the system can be in, defining execution histories precisely.' UNION ALL
SELECT 'What is fault tolerance?', 'The property describing whether a system can continue operating correctly in the presence of failures. Since failures are inevitable, fault-tolerant systems use redundancy and eliminate single points of failure.' UNION ALL
SELECT 'What are the Fallacies of Distributed Computing?', 'Peter Deutsch list (1994) of false assumptions: network is reliable, latency is zero, bandwidth is infinite, network is secure, topology does not change, there is one administrator, transport cost is zero, network is homogeneous.' UNION ALL
SELECT 'What is backpressure in distributed systems?', 'A strategy to handle producers publishing faster than consumers can process by slowing down producers. It prevents queues from growing unboundedly and helps maintain system stability under load.' UNION ALL
SELECT 'Why is assuming synchronized clocks dangerous in distributed systems?', 'Clocks drift between machines. Combined with latency-is-zero assumption, it causes problems in time-series processing. Unless using specialized high-precision sources, timestamps should not be used for synchronization or ordering.' UNION ALL
SELECT 'What is a fair-loss link?', 'A basic communication abstraction with three properties: (1) Fair loss - if sender keeps retransmitting infinitely, message eventually delivers; (2) Finite duplication - messages are not delivered infinitely many times; (3) No creation - link does not fabricate messages.' UNION ALL
SELECT 'What is a stubborn link?', 'A link abstraction where the sender keeps retransmitting messages indefinitely after timeout T. From the senders perspective, messages cannot get irrecoverably lost (assuming link stays intact), but this requires combining with acknowledgments for practicality.' UNION ALL
SELECT 'What is an idempotent operation?', 'An operation that can be executed multiple times yielding the same result without additional side effects. Example: server shutdown - first call initiates shutdown, subsequent calls have no effect. Important for safe retries in distributed systems.' UNION ALL
SELECT 'What is a perfect link?', 'A link abstraction providing: (1) Reliable delivery - messages from correct process A to correct process B eventually deliver; (2) No duplication - no message delivered more than once; (3) No creation - only delivers actually sent messages. Similar to TCP within a session.' UNION ALL
SELECT 'What is the Two Generals Problem?', 'A thought experiment showing agreement is impossible with asynchronous communication and link failures. Two generals must coordinate attack timing via messengers who can be captured. No matter how many ACKs are sent, neither can be certain the other will proceed.' UNION ALL
SELECT 'What is the FLP Impossibility?', 'Fischer, Lynch, Paterson proved that no completely asynchronous consensus algorithm can tolerate even a single process crash. Without timing assumptions, process failures cannot be reliably detected, so deterministic consensus in bounded time is impossible.' UNION ALL
SELECT 'What are the three properties of a correct consensus protocol?', '(1) Agreement - decision must be unanimous across all processes; (2) Validity - agreed value must be proposed by a participant (not predefined); (3) Termination - all processes must eventually reach a decision state.' UNION ALL
SELECT 'What is a synchronous vs asynchronous distributed system?', 'Synchronous: processes progress at comparable rates, transmission delays are bounded, message delivery cannot take arbitrarily long. Asynchronous: no timing assumptions, cannot reliably detect failures. Real systems are usually partially synchronous.' UNION ALL
SELECT 'What is a crash-stop failure model?', 'A failure model where a crashed process stops executing algorithm steps and sending messages, remaining in that state. Recovery is possible but the algorithm does not rely on it for correctness - process just participates in the next round.' UNION ALL
SELECT 'What is crash-recovery failure model?', 'A failure model where processes can stop executing but later recover and continue. Requires durable state and recovery protocol. Algorithms must consider all possible recovery states since recovering processes may continue from their last known step.' UNION ALL
SELECT 'What are omission faults?', 'Failures where a process skips algorithm steps, cannot execute them visibly, or cannot send/receive messages. Captures network partitions, slow nodes, lost messages. A crash can be simulated by completely omitting all messages to/from a process.' UNION ALL
SELECT 'What are Byzantine (arbitrary) faults?', 'Failures where a process executes algorithm steps but contradicts the algorithm (e.g., deciding on values no one proposed). Can be from bugs, version mismatches, or malicious actors. Hardest to handle; used in aerospace systems and cryptocurrencies.' UNION ALL
SELECT 'What is a network partition?', 'When two or more servers cannot communicate with each other. Can isolate groups that proceed independently, potentially producing conflicting results. Links can fail asymmetrically (A can reach B but not vice versa).' UNION ALL
SELECT 'How do backoff and jitter help with cascading failures?', 'Backoff: instead of immediate retry, clients wait increasing time periods between requests to avoid amplifying problems. Jitter: adds random delays to backoff to prevent different clients from retrying simultaneously after backoff period ends.'
) f WHERE m.name = 'Chapter 8: Introduction and Overview (Distributed Systems)' AND m.project_id = (SELECT id FROM projects WHERE name = 'Database Internals');

-- Chapter 8 FAQs
INSERT INTO faqs (module_id, question, answer, tags)
SELECT m.id, f.question, f.answer, f.tags FROM modules m,
(SELECT 'Why is distributed systems different from concurrent programming?' as question, 'In concurrent systems, processors can use shared memory to exchange information. In distributed systems, each processor has local state and participants communicate only by passing messages. This makes coordination harder and introduces network-related failure modes.' as answer, '["fundamentals", "concurrency"]' as tags UNION ALL
SELECT 'What does exactly-once delivery really mean?', 'Exactly-once delivery is about processing, not transport. TCP may retransmit packets multiple times, but deduplicates them so the message is processed once per session. True exactly-once requires common knowledge - all nodes agreeing the message was or was not persisted.', '["delivery-semantics", "messaging"]' UNION ALL
SELECT 'Why cannot we detect process failures reliably in asynchronous systems?', 'Without timing assumptions, there is no way to distinguish between a crashed process and a slow one. A process that does not respond might be dead, overloaded, or just experiencing network delays. This is why FLP proves consensus is impossible in purely asynchronous systems.', '["FLP", "failure-detection"]' UNION ALL
SELECT 'What is the practical implication of the Two Generals Problem?', 'It shows that perfect agreement over unreliable networks is impossible. In practice, we accept probabilistic guarantees: after enough ACKs, we proceed with high confidence. Systems use timeouts and retries rather than waiting for perfect certainty.', '["theory", "agreement"]' UNION ALL
SELECT 'How do circuit breakers help prevent cascading failures?', 'Circuit breakers monitor failures and allow fallback mechanisms. When a service starts failing, the breaker opens to stop sending requests, giving the service time to recover. This prevents one failure from overwhelming dependent services.', '["resilience", "patterns"]' UNION ALL
SELECT 'What is partial synchrony and why does it matter?', 'Partial synchrony means the system exhibits some synchronous properties (bounded delays) but bounds may not be exact and hold only most of the time. It is a realistic model for real systems and allows consensus algorithms like Raft and Paxos to work in practice.', '["timing", "system-models"]'
) f WHERE m.name = 'Chapter 8: Introduction and Overview (Distributed Systems)' AND m.project_id = (SELECT id FROM projects WHERE name = 'Database Internals');
